import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms and conditions for using TripMind.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
      <p className="text-[#8892b0] text-sm mb-8">Last updated: July 2026</p>

      <div className="space-y-8 prose-trip text-sm leading-relaxed">

        <section>
          <h2 className="text-lg font-semibold text-[#c7d2fe] mb-2">1. Acceptance</h2>
          <p className="text-[#8892b0]">By using TripMind, you agree to these terms. If you do not agree, please do not use the service.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#c7d2fe] mb-2">2. AI-generated content disclaimer</h2>
          <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 mb-3">
            <p className="text-amber-300 font-medium text-sm">⚠ Important — please read</p>
          </div>
          <ul className="text-[#8892b0] space-y-2 list-disc pl-5">
            <li>All itineraries, recommendations, visa information, flight prices, and hotel suggestions are <strong className="text-white">generated by AI</strong> and may be inaccurate, outdated, or incomplete.</li>
            <li>TripMind is <strong className="text-white">not a licensed travel agent</strong>, tour operator, or visa advisory service.</li>
            <li>Flight and hotel prices are <strong className="text-white">indicative estimates</strong> only — always verify current prices directly on the booking platform before purchasing.</li>
            <li>Visa information is <strong className="text-white">for reference only</strong> — always verify requirements with the official embassy or consulate of the destination country before travel.</li>
            <li>You are solely responsible for all travel decisions, bookings, and costs.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#c7d2fe] mb-2">3. No warranty</h2>
          <p className="text-[#8892b0]">TripMind is provided &quot;as is&quot; without any warranty of accuracy, availability, or fitness for a particular purpose. We do not guarantee that the service will be uninterrupted or error-free.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#c7d2fe] mb-2">4. Limitation of liability</h2>
          <p className="text-[#8892b0]">TripMind and its operators are not liable for any losses, damages, missed flights, denied visa applications, or travel disruptions arising from use of this service. This includes reliance on AI-generated itineraries, prices, or visa information.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#c7d2fe] mb-2">5. Acceptable use</h2>
          <p className="text-[#8892b0] mb-2">You agree not to:</p>
          <ul className="text-[#8892b0] space-y-1 list-disc pl-5">
            <li>Use automated scripts or bots to make excessive API calls</li>
            <li>Attempt to reverse-engineer or abuse the backend API</li>
            <li>Use the service for any unlawful purpose</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#c7d2fe] mb-2">6. Availability</h2>
          <p className="text-[#8892b0]">We reserve the right to modify, suspend, or discontinue TripMind at any time without notice. The service may be unavailable during maintenance or due to third-party API outages.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#c7d2fe] mb-2">7. Changes to terms</h2>
          <p className="text-[#8892b0]">We may update these terms at any time. Continued use after changes constitutes acceptance of the updated terms.</p>
        </section>

      </div>
    </div>
  );
}
